### ISSUE TITLE
Can't find any devices when using services

### ISSUE THREAD

**Issue by codeclinic** [sourcya/ble-tester#6]
If I add a service to the ScanBT function I am unable to find any devices.

So, if I remove the services and connect to a device I can verify the service UUID's that are available. Then If I add one of these as a service following the examples over at the `@capacitor-community/bluetooth-le` repo, the code / app fails to find any devices. This is true even if I use a generic UUID such as the Battery service that all GATT devices typically use.

```
    const TEST_SERVICE = numberToUUID(0x180f);

      await BleClient.initialize();
      const device = await BleClient.requestDevice({
        services: [TEST_SERVICE],
        //optionalServices: optionalService ? [optionalService] : [],
        //namePrefix: prefixFilter ? prefixFilter : '',
      });
```
Can you confirm that this works for you?

Thanks.

**Comment by codeclinic** [comment]
If I add a service UUID to your web demo and save it, it shows the same list of available devices as when I do a scan with no saved services.

This is true even if I add in a UUID for a service / product that I don't have. In this case I would expect no devices to be shown after the device scan.

Or have I totally misunderstood what the services option is ?

**Comment by mutasimissa** [comment]
First of all the web Bluetooth API still has problems, you need to test that on an android device to make sure.
Secondly, you shouldn't comment on the optionalServices in the object passed for requestDevice, instead, you can assign the value to an empty array, the same for prefix, you should pass an empty string.
From my experience which is not that big in GATT and BLE, the scan results without defining a service or optionalService depend on the manufacturer of the remote device you want to connect to, but generally you will get same results on most of devices, but when you want to read, notify or write (specially write) most manufacturers require that you pass their service UUID as the main service or optional service, I believe it has something to do with revealing the actual descriptors that the GATT server will use.
To summary my answer based on my latest work with a ble device, I got the same scan results when I added the service(s) UUID(s), but I couldn't;t subscribe to the notification or write unless I request device with passing the service UUID.
